=== marcusportmann/mmp-java/src/mmp-application-messaging/src/main/resources/META-INF/MessagingConfig.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT messaging (messageHandler*)>

  <!ELEMENT messageHandler (name, class, messages)>

    <!ELEMENT name ( #PCDATA )>

    <!ELEMENT class ( #PCDATA )>

    <!ELEMENT messages ( message* )>

      <!ELEMENT message EMPTY>

      <!ATTLIST message
        type  CDATA #REQUIRED
        typeVersion CDATA #REQUIRED
        isSynchronous CDATA #REQUIRED
        isAsynchronous CDATA #REQUIRED
        isArchivable CDATA #REQUIRED
      >

=== marcusportmann/mmp-java/src/mmp-application-messaging/src/main/resources/META-INF/MessagingConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE messaging SYSTEM "MessagingConfig.dtd">

<messaging>
  <messageHandler>
    <name>System Message Handler</name>
    <class>guru.mmp.application.messaging.handler.SystemMessageHandler</class>
    <messages>
      <!--  Authenticate Request Message -->
      <message type="d21fb54e-5c5b-49e8-881f-ce00c6ced1a3" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
      <!--  Registration Request Message -->
      <message type="3dbf238d-b56f-468a-8850-4ddf9f15c329" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
      <!--  Check User Exists Request Message -->
      <message type="cc005e6a-b01b-48eb-98a0-026297be69f3" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
      <!--  Test Request Message -->
      <message type="a589dc87-2328-4a9b-bdb6-970e55ca2323" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
      <!--  Another Test Request Message -->
      <message type="e9918051-8ebc-48f1-bad7-13c59b550e1a" typeVersion="1" isSynchronous="N" isAsynchronous="Y" isArchivable="Y"/>
      <!--  Message Part Download Test Request Message -->
      <message type="def49acc-426f-4e6a-ad31-78732e24c0c2" typeVersion="1" isSynchronous="N" isAsynchronous="Y" isArchivable="N"/>
      <!--  Submit Error Report Request Message -->
      <message type="ff638c33-b4f1-4e79-804c-9560da2543d6" typeVersion="1" isSynchronous="N" isAsynchronous="Y" isArchivable="N"/>
      <!--  Get Code Category Request -->
      <message type="94d60eb6-a062-492d-b5e7-9fb1f05cf088" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
      <!--  Get Code Category With Parameters Request -->
      <message type="3500a28a-6a2c-482b-b81f-a849c9c3ef79" typeVersion="1" isSynchronous="Y" isAsynchronous="N" isArchivable="N"/>
    </messages>
  </messageHandler>
</messaging>
